version: '2'
services:
  postgres-database:
    image: postgres:15
    container_name: postgres-measure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project_database
    ports:
      - "5432:5432"
    networks:
      - my-networks
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - 5000:5000
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge